site_name: Ethiopian Identity Provider
site_url: https://example.com
site_author: Mohamed Nesredin
site_description: >-
  Ethiopian Identity Provider platform

repo_name: Mohamed-Kaizen/ethiopian-identity-provider
repo_url: https://github.com/Mohamed-Kaizen/ethiopian-identity-provider/
edit_uri: ''

copyright: Copyright &copy; 2020 Mohamed Nesredin

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - tabs

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "etp.settings")
            - django.setup()
          rendering:
            show_source: true
      watch:
        - etp
        - users

nav:
  - Home: 'index.md'
  - BackEnd:
      - Setup: "backend/index.md"
      - Command: "backend/command.md"
      - Group and Staff: "backend/group_and_staff.md"
      - Load Dump Data: "backend/load_dump_data.md"
      - Handling Renew and Business Request: "backend/renew_and_businesses.md"
  - FrontEnd:
      - Setup: "frontend/index.md"
  - Reference:
      - Validationrs: "reference/validators.md"
      - Views: "reference/views.md"
      - Users:
          - Adapter: "reference/users/adapter.md"
          - Admin: "reference/users/admin.md"
          - Context Processors: "reference/users/context_processors.md"
          - Forms: "reference/users/forms.md"
          - Models: "reference/users/models.md"
          - Permissions: "reference/users/permissions.md"
          - Utils: "reference/users/utils.md"
          - Validators: "reference/users/validators.md"


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.details

extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'js/mermaid.min.js'
    - 'js/termynal.js'
    - 'js/custom.js'
